# Generated by Django 3.1.2 on 2020-10-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tytuł')),
                ('author', models.CharField(max_length=50, verbose_name='Autor')),
                ('pub_date', models.DateField(verbose_name='Data publikacji')),
                ('isbn', models.IntegerField(verbose_name='Numer ISBN')),
                ('pages', models.IntegerField(verbose_name='Liczba stron')),
                ('cover', models.URLField(verbose_name='Link do okładki')),
                ('lang', models.CharField(max_length=10, verbose_name='Język')),
            ],
        ),
    ]
