# Generated by Django 3.1.2 on 2020-10-12 19:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20201011_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Numer ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='lang',
            field=models.CharField(max_length=2, verbose_name='Język'),
        ),
    ]
